[package]
name = "module-01-basics"
version.workspace = true
edition.workspace = true

[dependencies]

[[example]]
name = "variables"
path = "examples/variables.rs"

[[example]]
name = "data_types"
path = "examples/data_types.rs"

[[example]]
name = "functions"
path = "examples/functions.rs"
